---
- name: Create a temp directory to store files needed by the run
  tempfile:
    state: directory
    prefix: "ansible-{{ role_name }}"
  register: _run_temp_dir
  notify:
    - delete temp items
- name: Create a temp directory for each cluster
  file:
    path: "{{ _run_temp_dir.path }}/{{ item.name }}"
    state: directory
    mode: "u=rwx,g=,o="
  loop: "{{ _cluster_ids | default([]) }}"
- name: Get the kubeconfig per cluster
  uri:
    url: "https://api.digitalocean.com/v2/kubernetes/clusters/{{ item.id | string }}/kubeconfig"
    method: GET
    headers:
      Authorization: "Bearer {{ digitalocean_api_token }}"
    return_content: yes
    status_code:
      - 200
  register: _cluster_configs
  loop: "{{ _cluster_ids | default([]) }}"
- name: Write the kubeconfig files
  copy:
    content: "{{ item.content }}"
    dest: "{{ _run_temp_dir.path }}/{{ item.item.name }}/kubectl.yaml"
    mode: "u=rwx,g=,o="
  loop: "{{ _cluster_configs.results | default([]) }}"
  no_log: true
