#
# @see https://raw.githubusercontent.com/kubernetes/ingress-nginx/master/deploy/provider/cloud-generic.yaml
#
---
kind: Service
apiVersion: v1
metadata:
  name: {{ ingress_service_name }}
  namespace: {{ ingress_service_name }}
  labels:
    app.kubernetes.io/name: {{ ingress_service_name }}
    app.kubernetes.io/part-of: {{ ingress_service_name }}
spec:
  externalTrafficPolicy: Local
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: {{ ingress_service_name }}
    app.kubernetes.io/part-of: {{ ingress_service_name }}
  ports:
{% foreach port as ingress_service_ports %}
    - name: {{ port.name }}
      port: {{ port.port }}
      targetPort: {{ port.targetPort }}
{% endfor %}